fix: unable to start Manager daemon due to reference error
Error raised:
AttributeError: 'UtilizationIdleChecker' object has no attribute 'cpu_threshold'